FROM node:16

WORKDIR /usr/src/app

COPY ./app ./app
COPY ./rln-client-lib ./rln-client-lib
COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json
COPY ./yarn.lock ./yarn.lock

RUN yarn install

RUN yarn workspace rln-client-lib build

EXPOSE 3000

CMD ["yarn", "app"]