FROM node:16

WORKDIR /usr/src/app

COPY ./server ./server
COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json
COPY ./yarn.lock ./yarn.lock

RUN yarn install

RUN yarn workspace server build

EXPOSE 8080
EXPOSE 8081

CMD ["yarn", "server"]