FROM node:16

WORKDIR /usr/src/app

COPY ./app ./app
COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json
COPY ./yarn.lock ./yarn.lock

RUN yarn install

EXPOSE 3000

CMD ["yarn", "app"]